# -*- coding: utf-8 -*-
"""Proyek Analisis Data_Wildan Sibil Danillah Safri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cg6EiR90S8jq1Evfjo2U_3ZtI-HjDu-

# Proyek Analisis Data Dicoding: [Bike Sharing Dataset]
- **Nama:** Wildan Sibil Danillah Safri
- **Email:** Wildansibil2@gmail.com
- **ID Dicoding:** https://www.dicoding.com/users/wildan_sibil

## Pertanyaan Analisis Bisnis Persewaan Sepeda

- Hubungan peran cuaca terhadap jumlah penyewa sepeda
- Perbandingan Tren jumlah penyewa sepeda pada tahun 2012 dan 2011

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime


from google.colab import drive
drive.mount('/content/drive')

"""**teks tebal**## Data Wrangling

# **Gathering Data**

# **1. Hour Data**
"""

day_df= pd.read_csv('/content/drive/MyDrive/E_bike_sharing/day.csv')
day_df.head()

"""# **2. Hour Data**"""

hr_df = pd.read_csv("/content/drive/MyDrive/E_bike_sharing/hour.csv")
hr_df.head()

"""### Assessing Data

# DATA DAY

Evaluasi Data Day
"""

day_df.info()

"""Checking Missing Data"""

day_df.isna().sum()

"""Checking Duplicate Data"""

print("Jumlah duplikasi data: ", day_df.duplicated().sum())

"""Checking Anomali Data"""

day_df.describe()

"""# DATA HOUR

Evaluasi Data Hour
"""

hr_df.info()

"""Checking Missing Data"""

hr_df.isna().sum()

"""Checking Duplicate Data"""

print("Jumlah duplikasi data: ", hr_df.duplicated().sum())

"""Checking Anomali Data"""

hr_df.describe()

"""# **Cleaning Data**

1. Menghapus tabel yang tidak diperlukan
"""

del hr_df

"""2. Menghapus beberapa kolom yang tidak akan digunakan"""

drop_col = ['instant', 'windspeed']

for i in day_df.columns:
  if i in drop_col:
    day_df.drop(labels=i, axis=1, inplace=True)

day_df.head()

"""3. Mengubah beberapa detail tentang kolom"""

# Mengubah nama judul kolom
day_df.rename(columns={
    'dteday': 'dateday',
    'yr': 'year',
    'mnth': 'month',
    'weathersit': 'weather_cond',
    'cnt': 'count'
}, inplace=True)

day_df.head()

# Mengubah angka menjadi keterangan
day_df['month'] = day_df['month'].map({
    1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun',
    7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'
})
day_df['season'] = day_df['season'].map({
    1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'
})
day_df['weekday'] = day_df['weekday'].map({
    0: 'Sun', 1: 'Mon', 2: 'Tue', 3: 'Wed', 4: 'Thu', 5: 'Fri', 6: 'Sat'
})
day_df['weather_cond'] = day_df['weather_cond'].map({
    1: 'Clear/Partly Cloudy',
    2: 'Misty/Cloudy',
    3: 'Light Snow/Rain',
    4: 'Severe Weather'
})

# Mengubah tipe data ke datetime
day_df['dateday'] = pd.to_datetime(day_df.dateday)

# Mengubaha tipe data ke categorical
day_df['season'] = day_df.season.astype('category')
day_df['year'] = day_df.year.astype('category')
day_df['month'] = day_df.month.astype('category')
day_df['holiday'] = day_df.holiday.astype('category')
day_df['weekday'] = day_df.weekday.astype('category')
day_df['workingday'] = day_df.workingday.astype('category')
day_df['weather_cond'] = day_df.weather_cond.astype('category')

day_df.head()

day_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore untuk Data DAY

1. Pengelompokan penyewa berdasarkan bulan
"""

day_df.groupby(by='month').agg({
    'count': ['max', 'min', 'mean', 'sum']
})

"""2. Pengelompokan penyewa berdasarkan keadaan cuaca"""

day_df.groupby(by='weather_cond').agg({
    'count': ['max', 'min', 'mean', 'sum']
})

"""3. Pengelompokan penyewa sepeda berdasarkan hari libur"""

day_df.groupby(by='holiday').agg({
    'count': ['max', 'min', 'mean', 'sum']
})

"""4. Perbandingan jumlah penyewa saat weeday dan weekend"""

day_df.groupby(by='weekday').agg({
    'count':['max','min','mean']
})

"""5. Pengelompokan penyewa berdasarkan weekday"""

day_df.groupby(by='workingday').agg({
    'count': ['max', 'min', 'mean']
})

"""6. Pengelompokan penyewa berdasarkan musim"""

day_df.groupby(by='season').agg({
    'casual': 'mean',
    'registered': 'mean',
    'count': ['max', 'min', 'mean']
})

"""7. pengelompokan temperature, hum, dan humidity berdasarkan musim"""

day_df.groupby(by='season').agg({
    'temp': ['max', 'min', 'mean'],
    'atemp': ['max', 'min', 'mean'],
    'hum': ['max', 'min', 'mean']
})

"""8. Hubungan antara penyewa casual, registered, dan count"""

fig, ax = plt.subplots(figsize=(10,6))
correlation_matrix = day_df.corr(numeric_only=True)
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))

sns.heatmap(
    correlation_matrix,
    annot=True,
    mask=mask,
    cmap="coolwarm",
    center=0,
    fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Hubungan peran cuaca terhadap jumlah penyewa sepeda
"""

plt.figure(figsize=(10,6))
sns.barplot(
    x='weather_cond',
    y='count',
    data=day_df)

plt.title('Jumlah Pengguna Sepeda berdasarkan Kondisi Cuaca')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Jumlah Pengguna Sepeda')
plt.show()

"""Bar plot ini menunjukkan bagaimana kondisi cuaca memengaruhi jumlah penyewaan sepeda. Jumlah penyewaan cenderung lebih tinggi saat cuaca cerah atau mendung, dan menurun drastis saat cuaca buruk, seperti hujan atau badai. Hal ini mencerminkan preferensi pengguna untuk menyewa sepeda ketika cuaca lebih bersahabat. Kondisi cuaca yang paling sering terjadi atau mendukung penyewaan sepeda dapat diidentifikasi dari bar tertinggi. Informasi ini berguna bagi pengelola layanan untuk memprediksi permintaan dan mengatur ketersediaan sepeda berdasarkan prakiraan cuaca.

**Insight:** Bar plot ini menunjukkan bagaimana kondisi cuaca memengaruhi jumlah penyewaan sepeda. Jumlah penyewaan cenderung lebih tinggi saat cuaca cerah atau mendung, dan menurun drastis saat cuaca buruk, seperti hujan atau badai. Hal ini mencerminkan preferensi pengguna untuk menyewa sepeda ketika cuaca lebih bersahabat. Kondisi cuaca yang paling sering terjadi atau mendukung penyewaan sepeda dapat diidentifikasi dari bar tertinggi. Informasi ini berguna bagi pengelola layanan untuk memprediksi permintaan dan mengatur ketersediaan sepeda berdasarkan prakiraan cuaca.

### Pertanyaan 2: Perbandingan Tren jumlah penyewa sepeda pada tahun 2012 dan 2011
"""

day_df['month'] = pd.Categorical(day_df['month'], categories=
    ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    ordered=True)

monthly_counts = day_df.groupby(by=["month","year"]).agg({
    "count": "sum"
}).reset_index()

sns.lineplot(
    data=monthly_counts,
    x="month",
    y="count",
    hue="year",
    palette="rocket",
    marker="o")

plt.title("Jumlah total sepeda yang disewakan berdasarkan Bulan dan tahun")
plt.xlabel(None)
plt.ylabel(None)
plt.legend(title="Tahun", loc="upper right")
plt.tight_layout()
plt.show()

"""**Insight:**
Dari grafik tersebut dapat terlihat bahwa jumlah penyewa pada tahun memiliki jumlah penyewa yang lebih banyak. Hal ini dapat dipengaruih oleh beberapa faktor antara lain :
- Kondisi cuaca yang lebih baik di tahun 2012 dibandingkan tahun 2011, sehingga lebih banyak orang tertarik menyewa sepeda.
- Musim tertentu seperti musim panas atau musim gugur mungkin lebih aktif dalam hal penyewaan sepeda.
- Hari kerja atau akhir pekan yang mungkin menunjukkan perbedaan pola penyewaan antara kedua tahun.

## Conclusion

- Dari grafik bar tersebut, dapat disimpulkan bahwa cuaca berperan signifikan dalam memengaruhi jumlah penyewaan sepeda. Jumlah pengguna sepeda paling tinggi ketika cuaca cerah atau sedikit berawan, dan menurun tajam saat cuaca semakin buruk, seperti hujan atau badai. Hal ini menandakan bahwa orang cenderung lebih suka menyewa sepeda dalam kondisi cuaca yang nyaman.

- Dari grafik garis tersebut dapat disimpulkan bahwa tren penyewaan sepeda dari bulan ke bulan dalam rentang dua tahun. Tren umum menunjukkan peningkatan jumlah penyewaan selama bulan-bulan musim panas, seperti Mei hingga September, dan penurunan selama musim dingin. Tahun 2012 memiliki jumlah penyewaan yang lebih tinggi dibandingkan 2011, yang bisa disebabkan oleh berbagai faktor seperti pertumbuhan layanan, cuaca yang lebih baik, atau promosi.
"""